USE ordermgr;

CREATE TABLE `item_type` (
  `ITEM_TYPE_ID` int(11) NOT NULL,
  `CODE` varchar(25) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `PARENT_ITEM_TYPE_ID` int(11) DEFAULT NULL,
  `ITEM_CATEGORY` varchar(20) DEFAULT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ITEM_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


