USE ordermgr;

CREATE TABLE `item_hist` (
  `ITEM_HIST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ITEM_ID` int(11) NOT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `UNIT_COST` double DEFAULT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ITEM_HIST_ID`),
  KEY `FK_ITEMHIST_ITEM` (`ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


