USE ordermgr;

CREATE TABLE `po_transaction` (
  `PO_TRANS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRANS_TYPE` varchar(20) NOT NULL,
  `PURCHASE_ORDER_ID` int(11) DEFAULT NULL,
  `TRANS_DATE` date DEFAULT NULL,
  `AMOUNT` decimal(6,0) DEFAULT NULL,
  `COMMENTS` varchar(1000) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PO_TRANS_ID`),
  KEY `FK_TRAN_PO` (`PURCHASE_ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


