USE ordermgr;

CREATE TABLE `purchase_order_items` (
  `PURCHASE_ORDER_ITEMS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUANTITY` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `UNIT_PRICE` double DEFAULT NULL,
  `DISCOUNT` double DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `PURCHASE_ORDER_ID` int(11) DEFAULT NULL,
  `ITEM_ID` int(11) DEFAULT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `DELETED` char(1) CHARACTER SET latin1 DEFAULT 'N',
  PRIMARY KEY (`PURCHASE_ORDER_ITEMS_ID`),
  KEY `fk_PURCHASE_order_item_item` (`ITEM_ID`),
  KEY `fk_PURCHASE_order_item_PURCHASE_order` (`PURCHASE_ORDER_ID`),
  CONSTRAINT `fk_PURCHASE_order_item_PURCHASE_order` FOREIGN KEY (`PURCHASE_ORDER_ID`) REFERENCES `purchase_order` (`PURCHASE_ORDER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


insert into `ordermgr`.`purchase_order_items`(`PURCHASE_ORDER_ITEMS_ID`,`QUANTITY`,`DESCRIPTION`,`UNIT_PRICE`,`DISCOUNT`,`AMOUNT`,`PURCHASE_ORDER_ID`,`ITEM_ID`,`CREATE_TS`,`UPDATE_TS`,`CREATED_BY`,`UPDATED_BY`,`DELETED`) values (1,1,'REPLACING BRAKE PADS FRONT AND REAR',220,0,220,2,1,'2014-07-22 21:19:00','2014-07-22 21:19:00',null,null,'N');
insert into `ordermgr`.`purchase_order_items`(`PURCHASE_ORDER_ITEMS_ID`,`QUANTITY`,`DESCRIPTION`,`UNIT_PRICE`,`DISCOUNT`,`AMOUNT`,`PURCHASE_ORDER_ID`,`ITEM_ID`,`CREATE_TS`,`UPDATE_TS`,`CREATED_BY`,`UPDATED_BY`,`DELETED`) values (2,1,'BALL JOINT x5',250,0,250,2,8,'2014-07-22 21:19:00','2014-07-22 21:19:00',null,null,'N');
