USE ordermgr;

CREATE TABLE `purchase_order` (
  `PURCHASE_ORDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PURCHASE_ORDER_NUM` varchar(11) DEFAULT NULL,
  `PURCHASE_ORDER_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PO_DESC` varchar(200) DEFAULT NULL,
  `DISCOUNT` decimal(6,0) DEFAULT NULL,
  `AMOUNT` decimal(6,0) DEFAULT NULL,
  `CUSTOMER_ID` int(11) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `DELETED` char(1) CHARACTER SET latin1 DEFAULT 'N',
  `PAYMENT_STATUS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`PURCHASE_ORDER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


insert into `ordermgr`.`purchase_order`(`PURCHASE_ORDER_ID`,`PURCHASE_ORDER_NUM`,`PURCHASE_ORDER_DATE`,`PO_DESC`,`DISCOUNT`,`AMOUNT`,`CUSTOMER_ID`,`STATUS`,`CREATE_TS`,`UPDATE_TS`,`CREATED_BY`,`UPDATED_BY`,`DELETED`,`PAYMENT_STATUS`) values (2,null,'2014-07-22 00:00:00','dfsdfs',null,470,10,'DRAFT','2014-07-22 21:19:00','2014-07-22 21:19:00',null,null,'N',null);
